//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMaker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ControlNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlMaker.ControlNames", typeof(ControlNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buzzer.
        /// </summary>
        public static string Buzzer {
            get {
                return ResourceManager.GetString("Buzzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grzałka.
        /// </summary>
        public static string Grzalka {
            get {
                return ResourceManager.GetString("Grzalka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napowietrzacz.
        /// </summary>
        public static string Napowietrzacz {
            get {
                return ResourceManager.GetString("Napowietrzacz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oświetlenie nocne.
        /// </summary>
        public static string Nocne {
            get {
                return ResourceManager.GetString("Nocne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Świetlówka 1.
        /// </summary>
        public static string Swietlowka1 {
            get {
                return ResourceManager.GetString("Swietlowka1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Świetlówka 2.
        /// </summary>
        public static string Swietlowka2 {
            get {
                return ResourceManager.GetString("Swietlowka2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Świetlówka 3.
        /// </summary>
        public static string Swietlowka3 {
            get {
                return ResourceManager.GetString("Swietlowka3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperatura.
        /// </summary>
        public static string Temperatura {
            get {
                return ResourceManager.GetString("Temperatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperatura maksymalna.
        /// </summary>
        public static string TempMax {
            get {
                return ResourceManager.GetString("TempMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperatura minimalna.
        /// </summary>
        public static string TempMin {
            get {
                return ResourceManager.GetString("TempMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lampa UV.
        /// </summary>
        public static string UV {
            get {
                return ResourceManager.GetString("UV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wentylator.
        /// </summary>
        public static string Wentylator {
            get {
                return ResourceManager.GetString("Wentylator", resourceCulture);
            }
        }
    }
}
